### ISSUE TITLE
Deployment Error - AccessControlListNotSupported: The bucket does not allow ACLs

### ISSUE THREAD

**Issue by peterjdavis** [aws-samples/amazon-rekognition-engagement-meter#94]
When deploying the template the Lambda function with Logical Id LambdaSetup is failing:

```
2023-11-01T15:13:27.701Z	3473ccf6-d08d-4527-8ead-6c56ce580109	INFO	AccessControlListNotSupported: The bucket does not allow ACLs
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9) {
  code: 'AccessControlListNotSupported',
  region: null,
  time: 2023-11-01T15:13:27.700Z,
  requestId: '<Redacted>',
  extendedRequestId: '<Redacted>',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 17.95203896988489
}
```
I'm guessing it could be related to https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

**Comment by matteofigus** [comment]
Hi @peterjdavis I believe this may happen if you have ACLs blocked in your account. If that's the case, you should deploy with "CreateCloudFrontDistribution" option set to true as explained in the doc: https://github.com/aws-samples/amazon-rekognition-engagement-meter#deployment

If that doesn't solve the issue, feel free to re-open it.
